Update
update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -88,11 +88,13 @@ jobs:
       # Step 8: SSH into server and deploy new containers
       - name: Deploy New Containers
         run: |
-          ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
-            set -x # Enable debug output
-            cd /home/ubuntu/Task_Test_Josimar_Backend
-            docker compose up -d --build
-          EOF
+            ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+              set -x
+              cd /home/ubuntu/Task_Test_Josimar_Backend
+              docker network create app-network || true
+              docker compose up -d --build || { echo "docker compose up failed"; exit 1; }
+              docker network ls
+            EOF
 
       # Step 9: Clean up SSH private key
       - name: Clean up SSH private key
@@ -195,6 +197,7 @@ jobs:
             sleep 10 # Add a delay
             curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_PUBLIC_IP }}:3000 || { echo "Grafana is not running"; exit 1; }
           EOF
+
       - name: Check prometheus and grafana from inside php-app.
         run: |
           ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
