Update with TEst block

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -85,26 +85,15 @@ jobs:
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/php-app:${{ env.COMMIT_ID }}
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/php-app:latest
 
-      # Step 8: SSH into server and deploy new containers and run tests
-      - name: Deploy New Containers and Run Tests
+      # Step 8: SSH into server and deploy new containers
+      - name: Deploy New Containers
         run: |
           ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
-              set -x # Enable debug output
-              set -x
-              cd /home/ubuntu/Task_Test_Josimar_Backend
-              docker compose up -d --build
-              docker compose run php-app composer install --no-interaction
-              docker compose run php-app php artisan migrate --force
-              echo "Starting tests..."
-              TEST_OUTPUT=$(docker compose run php-app php artisan test 2>&1) # Capture output
-              echo "$TEST_OUTPUT" # Display output
-              TEST_RESULT=$?
-              if [ $TEST_RESULT -ne 0 ]; then
-                echo "Tests failed. Deployment aborted."
-                docker compose down
-                exit 1
-              fi
-            EOF
+            set -x # Enable debug output
+            cd /home/ubuntu/Task_Test_Josimar_Backend
+            docker compose up -d --build
+          EOF
+
       # Step 9: Clean up SSH private key
       - name: Clean up SSH private key
         run: |
@@ -115,4 +104,37 @@ jobs:
       - name: Clean up known_hosts file
         run: |
           rm -f ~/.ssh/known_hosts
+        if: always()
+
+  test:
+    runs-on: ubuntu-latest
+    needs: build # run after the build job.
+
+    steps:
+      - name: Set up SSH key
+        run: |
+          echo "${{ secrets.EC2_KEY_PAIR_PEM }}" > private_key.pem
+          chmod 600 private_key.pem
+
+      - name: Run Tests
+        run: |
+          ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+            set -x
+            cd /home/ubuntu/Task_Test_Josimar_Backend
+            docker compose run php-app composer install --no-interaction
+            docker compose run php-app php artisan migrate --force
+            echo "Starting tests..."
+            TEST_OUTPUT=$(docker compose run php-app php artisan test 2>&1)
+            echo "$TEST_OUTPUT"
+            TEST_RESULT=$?
+            if [ $TEST_RESULT -ne 0 ]; then
+              echo "Tests failed. Deployment aborted."
+              docker compose down
+              exit 1
+            fi
+          EOF
+
+      - name: Clean up SSH private key
+        run: |
+          rm -f private_key.pem
         if: always()
