Update
update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -90,8 +90,20 @@ jobs:
         run: |
           ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
               set -x # Enable debug output
+              set -x
               cd /home/ubuntu/Task_Test_Josimar_Backend
               docker compose up -d --build
+              docker compose run php-app composer install --no-interaction
+              docker compose run php-app php artisan migrate --force
+              echo "Starting tests..."
+              TEST_OUTPUT=$(docker compose run php-app php artisan test 2>&1) # Capture output
+              echo "$TEST_OUTPUT" # Display output
+              TEST_RESULT=$?
+              if [ $TEST_RESULT -ne 0 ]; then
+                echo "Tests failed. Deployment aborted."
+                docker compose down
+                exit 1
+              fi
             EOF
       # Step 9: Clean up SSH private key
       - name: Clean up SSH private key
