Update
update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -131,21 +131,20 @@ jobs:
             cd /home/ubuntu/Task_Test_Josimar_Backend
             docker compose run php-app composer install --no-interaction
             docker compose run php-app php artisan migrate --force
-            
             echo "Running tests..."
-            # Run tests and capture the exit code properly
-            docker compose run php-app php artisan test
-            TEST_RESULT=$?
-            
-            # Check the test result
+            docker compose run php-app php artisan test | tee test_output.txt
+            echo "Tests completed."
+            ls -l test_output.txt
+            echo "Displaying test output:"
+            cat test_output.txt
+            TEST_RESULT=\${PIPESTATUS[0]}
             if [ $TEST_RESULT -ne 0 ]; then
-              echo "Tests failed with exit code $TEST_RESULT. Deployment aborted."
+              echo "Tests failed. Deployment aborted."
               docker compose down
               exit 1
-            else
-              echo "Tests passed successfully!"
             fi
           EOF
+
 
       - name: Clean up SSH private key
         run: |
