Update
update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -176,6 +176,7 @@ jobs:
           echo "${{ secrets.EC2_KEY_PAIR_PEM }}" > private_key.pem
           chmod 600 private_key.pem
 
+      #Step 3: Check if Prometheus and Grafana are running
       - name: Check Prometheus Service
         run: |
             ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
@@ -190,6 +191,7 @@ jobs:
               curl -s -o /dev/null -w "%{http_code}" http://prometheus:9090 || { echo "Prometheus is not running"; exit 1; }
             EOF
 
+      #Step 4: Check if Grafana is running
       - name: Check Grafana Service
         run: |
           ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
@@ -197,17 +199,17 @@ jobs:
             cd /home/ubuntu/Task_Test_Josimar_Backend
             echo "Checking if Grafana is running..."
             sleep 10 # Add a delay
-            curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_PUBLIC_IP }}:3000 || { echo "Grafana is not running"; exit 1; }
+            curl -s -o /dev/null -w "%{http_code}" http://grafana:3000 || { echo "Grafana is not running"; exit 1; }
           EOF
 
+      # Step 5: Clean up SSH private key
       - name: Check prometheus and grafana from inside php-app.
         run: |
           ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
             set -x
             cd /home/ubuntu/Task_Test_Josimar_Backend
             echo "Checking prometheus from php-app"
-            docker compose run php-app curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_PUBLIC_IP }}:9090 || { echo "Prometheus is not running from php-app"; exit 1; }
+            docker compose run php-app curl -s -o /dev/null -w "%{http_code}" http://prometheus:9090 || { echo "Prometheus is not running from php-app"; exit 1; }
             echo "Checking grafana from php-app"
-            docker compose run php-app curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_PUBLIC_IP }}:3000 || { echo "Grafana is not running from php-app"; exit 1; }
-
+            docker compose run php-app curl -s -o /dev/null -w "%{http_code}" http://grafana:3000 || { echo "Grafana is not running from php-app"; exit 1; }
           EOF
