Update
update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,8 +47,16 @@ jobs:
       - name: Clean up old Docker containers
         run: |
           ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
-            mkdir -p /home/ubuntu/Task_Test_Josimar_Backend
-            cd /home/ubuntu/Task_Test_Josimar_Backend
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker could not be found, installing Docker..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sh get-docker.sh
+              sudo usermod -aG docker $USER
+              newgrp docker
+            fi
+            mkdir -p /home/ubuntu/Task_Test_Backend
+            cd /home/ubuntu/Task_Test_Backend
             docker compose down
             docker system prune -af
           EOF
